### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by LavaCreeperYT** [Level-Share-Square/SMC-translations#4]
I could do a Russian translation for the game, but I'm afraid it doesn't support Cyrillic characters

**Comment by LavaCreeperYT** [comment]
Аа Бб Вв Гг Дд Ее Ёё Жж Зз Ии Йй Кк Лл Мм Нн Оо Пп Рр Сс Тт Уу Фф Хх Цц Чч Шш Щщ Ъъ Ыы Ьь Ээ Юю Яя

List of Russian letters (uppercase and lowercase)

**Comment by Luigibonus** [comment]
Those letters shouldn't be an issue in theory, so feel free to contribute to the translation if you like. It's a lot of letters tho, so I can make them after the translation is completed

**Comment by LavaCreeperYT** [comment]
[ru-RU.json](https://github.com/Level-Share-Square/SMC-translations/files/14019088/ru-RU.json)
Here is the translation file, I hope it will work

**Comment by Luigibonus** [comment]
Since you may want to update the translation file in the future, let me show you how you can do it yourself:

1) Go to https://github.com/Level-Share-Square/SMC-translations/fork
2) Then, in your forked repository, press the **Add file** button at the top and insert the **ru-RU.json** file
3) In your forked repository, press **Pull requests** at the top-left, and then **New pull request** (the green button). Then press 'Create pull request'.

After that, your changes will be queued for approval here on the SMC-translations repo! Let me know if you have questions, I'll put this info on the main page soon as well.
